<a href="https://colab.research.google.com/github/ghoshal7/python_basics/blob/master/numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
NumPy (short for Numerical Python) is a powerful package to do data science/ analytics. It provides an efficient interface to store and operate dense data buffers, and it could help us perform mathmatical operation on vectors, matrices and arrays.

In [0]:
import numpy
# We could also check the current NumPy version
numpy.version.version

'1.14.6'

In [0]:
# We could also create an "alias" for our convience.
# Here, we use "np" to stand for NumPy.
import numpy as np

# The same result.
np.version.version

'1.14.6'

In [0]:
# An example one-dimensional Numpy array. By default, the numbers are considered integers.
a = np.array([1,2,3,4,5])
print(a)

print(np.ndim(a))

print(np.size(a))

print(np.shape(a))

print(np.mean(a))

print(np.std(a))

[1 2 3 4 5]
1
5
(5,)
3.0
1.4142135623730951


In [0]:
# Can instead specify that values are floats.
a = np.array([1,2,3,4,5], dtype = np.float64)
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float64


In [0]:

# A two-dimensional Numpy array.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.ndim(b))

2


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## Useful function

**1.   Reshaping**



In [0]:
a = np.array(list(range(1,17))).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [0]:
print('Reverse order')
print(a[::-1])

print('Convert to 1D - flatten')
print(a.reshape(-1))  # are they all same?
print(a.flatten()) 
print(np.ravel(a))

print('rectangular reshaping')
print(a.reshape(2,8))

print('increase ndim')
print(a.reshape(2,2,4))

Reverse order
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Convert to 1D - flatten
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
rectangular reshaping
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
increase ndim
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


**2.   Range / Linspace**

Create regularly-spaced numbers on an interval. 

'**linspace**'- to specify **number of values** 

'**arange**' - to specify the **step length**. 

Notice that 'linspace' includes the final endpoint while 'arange' does not.


In [0]:
print(np.linspace(0, 10, 5))
print(np.arange(0, 12.5, 2.5)) # does not include the end value

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [0]:
print(list(range(0,12)))
print(list(range(0,12,2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 2, 4, 6, 8, 10]


In [0]:
print(np.logspace(1,10, 5, base = 10)) # NOTE: linspace and logspace - by default prints 50 values

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]




**3. Operations**





In [0]:
a = np.arange(1,10).reshape(3,3)
b = np.copy(a)
print('SUM')
c = a+b
print(c)
print('for same matrix using axis')
print(c.sum(axis=1)) #elements of same row added
print()
print('ELEMENT WISE MULTIPLICATION')
print(a*b)
print()
print('DOT PRODUCT') #remember : dot product of 2 matrix is matrix ==> n,p X p,m = n,m
print(np.dot(a,b))
print()
print('TRANSPOSE')
print(a.T)

SUM
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
for same matrix using axis
[12 30 48]

ELEMENT WISE MULTIPLICATION
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

DOT PRODUCT
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

TRANSPOSE
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**4. Special matrix**

In [0]:
print('ONES')
print(np.ones((2,3)))
print()
print('ZEROS')
print(np.zeros((3,3)))
print()
print('1 @ diag ==> EYE')
print('k = 0')
print(np.eye(M=3, N=3, k = 0))
print('k = 1')
print(np.eye(M=3, N=3, k = 1))
print('k = -1')
print(np.eye(M=5, N=3, k = -1))

ONES
[[1. 1. 1.]
 [1. 1. 1.]]

ZEROS
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

1 @ diag ==> EYE
k = 0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
k = 1
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
k = -1
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


**5. Special functions**

In [0]:
# exponential function
x = np.array([1,2,3])
print('sigmoid_x = ',1/(1+np.exp(-x)))

sigmoid_x =  [0.73105858 0.88079708 0.95257413]


In [0]:
# normalizing -- x/||x||
x = np.array([[1,2,3],[4,5,6]])
mod_x = np.linalg.norm(x)
print(x/mod_x, '\n', 'mod value = ', mod_x)

[[0.10482848 0.20965697 0.31448545]
 [0.41931393 0.52414242 0.6289709 ]] 
 mod value =  9.539392014169456


## Vectorization with numpy

In [0]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###  Note: Outer product = xx' (which gives a matrix, by col X row)
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
#print ("outer = " + str(outer))
print('--- Computation time = '+str(1000*(toc - tic)) + "ms")
      
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
#print ("outer = " + str(outer))
print('--- Computation time = ' + str(1000*(toc - tic)) + "ms")

--- Computation time = 0.2717210000002801ms
--- Computation time = 0.1454009999997119ms
