# Control Flow Statements

### Logical operation
- IF 
- IF - ELSE
- IF - ELIF - ELSE

In [4]:
x =10

In [5]:
if (x>5):
    print('Howdy!')

Howdy!


In [6]:
if (x >100):
    print('x is large')
else:
    print('x is small')

x is small


In [16]:
if x >100:
    print('x is large')
elif (x > 5):
    print('x is OK')
else:
    print('x is small')

x is OK


### Loop operations
- for
- while

In [32]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- ** for loops **

In [17]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [33]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for lst in list_of_lists:
        print (lst)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [34]:
# Nested Loops
for i in list_of_lists:
    for j in i:
        print(i,j)
        #print(i,'-->',j)

[1, 2, 3] 1
[1, 2, 3] 2
[1, 2, 3] 3
[4, 5, 6] 4
[4, 5, 6] 5
[4, 5, 6] 6
[7, 8, 9] 7
[7, 8, 9] 8
[7, 8, 9] 9


- ** while loops **

In [44]:
i = 1
while i < 5:
    print(i)
    i = i+1
print('Bye')

1
2
3
4
Bye


### Break

As the name says. It is used to break out of a loop when a condition becomes true when executing the loop.

In [45]:
a = 10
for i in range(100):
    print (i)
    if i>=a:
        break

0
1
2
3
4
5
6
7
8
9
10


### Continue

This continues the rest of the loop. Sometimes when a condition is satisfied there are chances of the loop getting terminated. This can be avoided using continue statement. 

In [59]:
for i in range(10):
#     if i==0:
#         continue
    print (i)

0
1
2
3
4
5
6
7
8
9


### List Comprehensions

Python makes it simple to generate a required list with a single line of code using list comprehensions**(probably the most valueable tool**). For example If i need to generate multiples of say 27 I write the code using for loop as,

In [60]:
res = []
for i in range(1,11):
    x = 27*i
    res.append(x)
print (res)

[27, 54, 81, 108, 135, 162, 189, 216, 243, 270]


Since you are generating another list altogether and that is what is required, List comprehensions is a more efficient way to solve this problem.

In [61]:
[27*x for x in range(1,11)]

[27, 54, 81, 108, 135, 162, 189, 216, 243, 270]

you might be wondering can nested loops be extended to list comprehensions? Yes you can.

In [65]:
[27*x for x in range(1,21) if x>10]

[297, 324, 351, 378, 405, 432, 459, 486, 513, 540]

### Functions

This is the basic syntax of a function
def funcname(arg1, arg2,... argN):
    
    ''' Document String'''

    statements


    return <value>

In [66]:
def firstfunc(x,y):
    z = x + y
    return (z)

firstfunc(2,3)

5

In [85]:
def add_n(*args):
    sums = 0
    for i in args:
        sums = sums + i
    return(sums)
    #print('sum of entries = ', sums)

In [94]:
def additional_n(*args):
    sums = 0
    multiples = 1
    for i in args:
        sums = sums + i
        multiples = multiples*i
    return(sums, multiples)
#     return({'sumsss = ': sums,
#             'multies' : multiples})

### Global and Local Variables

Whatever variable is declared inside a function is local variable and outside the function in global variable.

In [97]:
eg1 = [1,2,3,4,5]

In [98]:
def egfunc1():
    print ("This is happening before the function is called : ", eg1)
    
    def thirdfunc(arg1):
        eg2 = arg1[:]
        eg2.append(6)
        print ("This is happening inside the function :", eg2) 
    thirdfunc(eg1)
    
    print ("This is happening outside the function :", eg1)   
    
    print ("Accessing a variable declared inside the function from outside :" , eg2)

In [99]:
egfunc1()

This is happening before the function is called :  [1, 2, 3, 4, 5]
This is happening inside the function : [1, 2, 3, 4, 5, 6]
This is happening outside the function : [1, 2, 3, 4, 5]


NameError: name 'eg2' is not defined

If a **global** variable is defined as shown in the example below then that variable can be called from anywhere.

In [101]:
def egfunc1():
    def thirdfunc(arg1):
        global eg2
        eg2 = arg1[:]
        eg2.append(6)
        print ("This is happening inside the function :", eg2) 
    print ("This is happening before the function is called : ", eg1)
    thirdfunc(eg1)
    print ("This is happening outside the function :", eg1)   
    print ("Accessing a variable declared inside the function from outside :" , eg2)

In [102]:
egfunc1()

This is happening before the function is called :  [1, 2, 3, 4, 5]
This is happening inside the function : [1, 2, 3, 4, 5, 6]
This is happening outside the function : [1, 2, 3, 4, 5]
Accessing a variable declared inside the function from outside : [1, 2, 3, 4, 5, 6]


# Package #
A package is the module, or in other words, a collection of relevant entitles, that could be added to a program (e.g., Python) to add additional options, features and functionality. 
There are many useful packages for Python, and NumPy is a common and extensively used one.
We start from NumPy.

In [ ]:
# Why error?
print(pi)
#print(sqrt(4))

In [105]:
# from and import function to import a particular "object" from a specific package.

from math import pi
print(pi)

#from math import *

3.141592653589793


# NumPy #
NumPy (short for *Numerical Python*) is a powerful package to do data science/ analytics. It provides an efficient interface to store and operate dense data buffers, and it could help us perform mathmatical operation on vectors, matrices and arrays.

In [1]:
import numpy
# We could also check the current NumPy version
numpy.version.version

'1.13.3'

In [1]:
# We could also create an "alias" for our convience.
# Here, we use "np" to stand for NumPy.
import numpy as np

# The same result.
np.version.version

'1.13.3'

In [3]:
# An example one-dimensional Numpy array. By default, the numbers are considered integers.
a = np.array([1,2,3,4,5])
print(a)

print(np.ndim(a))

print(np.size(a))

print(np.shape(a))

print(np.mean(a))

print(np.std(a))

[1 2 3 4 5]
1
5
(5,)
3.0
1.41421356237


In [4]:
# Can instead specify that values are floats.
a = np.array([1,2,3,4,5], dtype = np.float64)
print(a)
print(a.dtype)

[ 1.  2.  3.  4.  5.]
float64


In [9]:
# A two-dimensional Numpy array.
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.ndim(b))

2


In [129]:
np.shape(b)

(2, 5)

In [130]:
np.reshape(b, [5,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [132]:
# Create regularly-spaced numbers on an interval. 
# Use 'linspace' if you want to specify the number of values to create
# 'arange' if you want to specify the step length. 
# Notice that 'linspace' includes the final endpoint while 'arange' does not.

print(np.linspace(0, 10, 5))
print(np.arange(0, 12.5, 2.5))

[  0.    2.5   5.    7.5  10. ]
[  0.    2.5   5.    7.5  10. ]


In [23]:
print(list(range(0,12)))
print(list(range(0,12,2)))

#print(list(range(0, 12.5, 2.5)))

# def frange(x, y, jump):
#     while x < y:
#         x += jump
#         print(x)

# frange(0,12.5,2.5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[0, 2, 4, 6, 8, 10]


In [30]:
# 'Stacking' arrays together. Use 'vstack' to stack vertically and 
# 'hstack' to stack horizontally. 
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print('a=', a,';','b =', b)
print('vstack = ','\n', np.vstack([a,b]))
print('hstack = ', np.hstack([a,b]))

a= [1 2 3 4] ; b = [10 20 30 40]
vstack =  
 [[ 1  2  3  4]
 [10 20 30 40]]
hstack =  [ 1  2  3  4 10 20 30 40]


In [36]:
Transpose an array.
c = [[7,8,9],[70,80,90]]
print(c)
print(c.transpose())

c = np.array([[7,8,9],[70,80,90]])
print(c)
print(c.transpose())

[[ 7  8  9]
 [70 80 90]]
[[ 7 70]
 [ 8 80]
 [ 9 90]]
